name: root
description: Flutter Plugin to check Android device Root status and Run shell commands in android(only), use this plugin only for short period of processes.
homepage: https://github.com/gokul1630/root

version: 1.0.5+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: com.gokul.root
        pluginClass: RootPlugin
